import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import navLinks from './const/navLinks'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='p-10 font-mono'>
        <nav className='bg-blue-400 p-5 flex justify-center'>
          {navLinks.map(link => (
              <Link href={link.path} className='shadow md:w-40 bg-blue-50 p-2 m-2 text-center hover:bg-gray-50'>
                {link.label} 
              </Link>
          ))}
          </nav>
          <main className='bg-gray-100 p-5'>
          {children}
          </main>
          <footer className='bg-blue-400 p-5 text-gray-100 text-center'>
            {new Date().getFullYear()}
          </footer>
        </div>
        </body>
    </html>
  )
}
